# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8138180d43d3a266cd5d90fa35d11bef66a63965ef39e7d390bdddc332bfa9d82068572ff069640cd42c2c62f1a9f59542ae826273d0eaeab20312ead6fe5ac1

test:
  secret_key_base: 5fd04d5cd54c606feabaf5a9b50b8e067f49474ac02a2b989735d863404842f9285c922c9a073682ffbc666e132c04ec1848dc1b96c707b5eaa256c885590ca7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
